# Generated by Django 5.2.8 on 2025-12-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên mặt hàng')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã SKU')),
                ('category', models.CharField(max_length=100, verbose_name='Ngành hàng')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá bán')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('mode', models.CharField(choices=[('PRODUCT', 'Sản phẩm'), ('IMPORT', 'Nhập kho'), ('EXPORT', 'Xuất kho')], default='PRODUCT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
