# Generated by Django 5.2.8 on 2025-12-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Ngành hàng')),
            ],
        ),
        migrations.CreateModel(
            name='ImportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=50, unique=True)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên mặt hàng')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã SKU')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá bán')),
                ('cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá nhập')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('mode', models.CharField(choices=[('PRODUCT', 'Sản phẩm'), ('IMPORT', 'Nhập kho'), ('EXPORT', 'Xuất kho')], default='PRODUCT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CNPM2.category', verbose_name='Ngành hàng')),
            ],
        ),
        migrations.CreateModel(
            name='ImportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_quantity', models.IntegerField(default=1)),
                ('imported_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNPM2.importreceipt')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CNPM2.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='importreceipt',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CNPM2.supplier'),
        ),
    ]
