# Generated by Django 5.2.8 on 2025-12-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNPM2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=50, unique=True, verbose_name='Mã Phiếu Xuất')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='Người nhận hàng')),
                ('export_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày xuất')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('COMPLETED', 'Đã xuất kho'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng giá trị xuất')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Thông tin liên hệ'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='imported_price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='imported_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CNPM2.inventoryitem', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='importdetail',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='CNPM2.importreceipt'),
        ),
        migrations.AlterField(
            model_name='importreceipt',
            name='receipt_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã Phiếu Nhập'),
        ),
        migrations.AlterField(
            model_name='importreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CNPM2.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá vốn (đ)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='mode',
            field=models.CharField(default='PRODUCT', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá bán (đ)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên nhà cung cấp'),
        ),
        migrations.CreateModel(
            name='ExportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_quantity', models.IntegerField(verbose_name='Số lượng xuất')),
                ('exported_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá xuất')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CNPM2.inventoryitem', verbose_name='Sản phẩm')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_details', to='CNPM2.exportreceipt')),
            ],
        ),
    ]
